### ISSUE TITLE
🪲[Bug]: Cannot Install GitHub module from PSGallery

### ISSUE THREAD

**Issue by brianwest** [PSModule/Build-PSModule#86]
### Describe the bug

The task is unable to install the GitHub module.

### Version information

v2

### To reproduce

It looks like the setup for the action is failing so I believe it would fail regardless of the inputs used.

### Code snippet

```YAML
name: Build-PSModule

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/psmodule.yml'
  workflow_dispatch:

jobs:
  Build-PSModule:
    name: Build-PSModule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Install GitHub PowerShell Module
        shell: pwsh
        run: Install-Module -Name GitHub -Force

      - name: Build PSModule
        uses: PSModule/Build-PSModule@v2
        with:
          Name: GitHubTools
          Version: 1.0.4
```

### Relevant output

![Image](https://github.com/user-attachments/assets/9e2f0a3c-758e-4a9c-9e8c-af9ac83fecf0)
